### ISSUE TITLE
Question: how does this project relate to cvelistV5

### ISSUE THREAD

**Issue by henrirosten** [fkie-cad/nvd-json-data-feeds#2]
How does this project relate to https://github.com/CVEProject/cvelistV5?

**Comment by rhelmke** [comment]
Hey,

1. **Involved Parties.** cvelistV5 is MITRE's official file-based cache of the CVE data set. This repository is a community effort to basically implement the same for the NVD data set. It is important to note that *this repository is neither endorsed by nor affiliated with the NVD*.
2. **It is not the same data.** We cache the NVD data set, not MITRE. The NVD synchronizes with MITRE for CVE information. The NVD exists because it [adds various meta data to CVE records](https://nvd.nist.gov/general/FAQ-Sections/General-FAQs#faqLink0). Namely [CVSS](https://nvd.nist.gov/vuln-metrics/cvss) calculations, further continuously  updated technical references, [CPEs](https://nvd.nist.gov/products), and supplementary [CWE](https://nvd.nist.gov/vuln/categories) meta data. While newer CVEs in the MITRE DB contain CWE and CVSS data as well, e.g. [CVE-2022-2942](https://github.com/CVEProject/cvelistV5/blob/b68a3fa493db604596192c21140a1e590a6b81ff/cves/2022/4xxx/CVE-2022-4942.json), there is a significant amount of items without such info. Yet they are present in the NVD; take Heartbleed's CVE-2014-0160 as an example: Compare the bug data in [this repo](https://github.com/fkie-cad/nvd-json-data-feeds/blob/main/CVE-2014/CVE-2014-01xx/CVE-2014-0160.json) with [cvelistV5](https://github.com/CVEProject/cvelistV5/blob/main/cves/2014/0xxx/CVE-2014-0160.json). One of them neither contains CWE nor CVSS data. Also, MITRE does not incorporate CPEs, which are *very* convenient for automated version-based matching of affected products.
3. **The format is different**. cvelistV5 uses [CVE JSON 5.0](https://github.com/CVEProject/cve-schema/blob/master/schema/v5.0/CVE_JSON_5.0_schema.json), this repository caches [NVD API 2.0 JSON](https://csrc.nist.gov/schema/nvd/api/2.0/cve_api_json_2.0.schema) responses.
4. **Release Packages.** This repository releases packages that aim to resemble the [Legacy NVD Data Feeds](https://nvd.nist.gov/vuln/data-feeds#vuln-feed-table), take a look at our [Release Page](https://github.com/fkie-cad/nvd-json-data-feeds/releases) and compare the downloadable assets :). We wanted a drop-in replacement for said feeds. They are used in several of our software projects. For example [FACT](https://github.com/fkie-cad/FACT_core).

There are several other differences not mentioned here. However, in my opinion these are the key differences. :-)

**Comment by rhelmke** [comment]
I hope you don't mind that I pinned this issue. I think this is a very legitimate question to ask :-).
